language: java # Define the language

jdk: # Define the execution environments
 - openjdk8
 
branches: # Execute job only on specific branch commits
 only:
 - main
 - development
 
 env:
  global:
    - CODECOV_TOKEN=5c624de2-e7c6-4534-9506-9b83e7190d9b
 
before_script: # Run commands
 - ls -la
 
script: # Build the project
 - mvn clean package jacoco:report cobertura:cobertura
 
after_success: # Notify users about the result
 - bash <(curl -s https://codecov.io/bash) -t 5c624de2-e7c6-4534-9506-9b83e7190d9b
 - echo “Process terminated successfully”
