language: java # Define the language

jdk: # Define the execution environments
 - openjdk8
 
branches: # Execute job only on specific branch commits
 only:
 - main
 - development
 
before_script: # Run commands
 - ls -la
 
script: # Build the project
 - mvn clean package jacoco:report coveralls:report cobertura:cobertura
 
after_success: # Notify users about the result
 - echo “Process terminated successfully”
